#해당 디렉토리(native-local-repo)에 있는 yml 파일들위에 상위로 application.yml이 있다.
#/yml파일명/default 호출시 공통적으로 application.yml을 불러오기 때문에 공통적으로 모두 적용하고 싶은 값이 있다면 application.yml에 명시하면된다 (ex. token에 대한 key)
token:
  secret: ndc-token-secret-key
  access_expiration: 86400000 # 1일
  refresh_expiration: 604800000 # 7일
  #{cipher} 를 앞에 붙히면 어플리케이션에게 암호화된 글자라는 의미를 전달하여 일반텍스트로 읽게하지 않는다.
dev:
 secret: dev-secret2