#해당 디렉토리(native-local-repo)에 있는 yml 파일들위에 상위로 application.yml이 있다.
#/yml파일명/default 호출시 공통적으로 application.yml을 불러오기 때문에 공통적으로 모두 적용하고 싶은 값이 있다면 application.yml에 명시하면된다 (ex. token에 대한 key)
token:
  access_expiration: 86400000 #60 * 60 * 24 * 1000 (1일 계산)
  refresh_expiration: 604800000 #60 * 60 * 24 * 1000 (1일 계산)
  secret: '{cipher}AQBTDABbD+L4d7Xm+970WJmasy5yUCaZNyOxSWkvfhMxVAjBqQjuUBEpvBPiLDXt82P9+XnW1ihDqjupTvX5Pim4P8EaLwxGvn7Ws7ep7lCkxSowm/MidhdCrY+wxK35MMn8brFrIzDxVBJzuTMc95MgEdQN2q92tcuxNqPGNb2Cz+jzshRGJWeqOHSIDWPB1TM8LTnkZyMvBQ756S5Kb1iNdsOANAYhn+CnhSbu/vGmkUOhiKu7Vc9iVwfzZ3e+WW3r/07aajffSCFU0+2nATYmCWHkZocxgetyp4a9uXcNqks/y4grfe/yQORYaTeE8cYsgNhDKBqHgcJ3BvVzZxBcV0GtVw8mYLkVV4u1tLmMDnUkk6rWFUbZufUisMU7Cl2kq9ipbdmhfEVHGe3pGUm1f8t3kKABYpjgqJRwjIo3cEzpRJ/eEp2G90eOeg5IcTh4yzcwiD/bbw8mj0kXlZCN'
  #{cipher} 를 앞에 붙히면 어플리케이션에게 암호화된 글자라는 의미를 전달하여 일반텍스트로 읽게하지 않는다.
dev:
  secret: dev-secret2