#해당 디렉토리(native-local-repo)에 있는 yml 파일들위에 상위로 application.yml이 있다.
#/yml파일명/default 호출시 공통적으로 application.yml을 불러오기 때문에 공통적으로 모두 적용하고 싶은 값이 있다면 application.yml에 명시하면된다 (ex. token에 대한 key)
token:
  access_expiration: 86400000 #60 * 60 * 24 * 1000 (1일 계산)
  refresh_expiration: 604800000 #60 * 60 * 24 * 1000 (1일 계산)
  secret: '{cipher}AQCXywx7TyqFWOg2GpSJmX+cvfI8sgdFCcjT5CImDFHAKIDvnqtcgsCJeHhMWXHaqtq6IjKNrX1LJeyOzb6cUCe49d5nQg7HcuLJVUqmCDn9YE9jStI612elS9zhW5PH6ZdbEZ9GGIHFHOIi5/S5YfC9L9af7/Ft3PzVeavDrTYyu9JKblVC0+8kj1XWY8bIyJfbDJBEUMubH9F2RdYfgRMbLKszbkAyqJtZ8Kj9hsEnnrH3gd0l6d5VyNN9YOu3EUet+hkO8QZqtPeGB0+B+BySAk3ZTs+CwJcNexes0m0SCMQ8WIhH60ajAmCFKYvHMO733ePxFX/zN7BLCxa42H4kmwFvKtCgiJjx/mZh9Kb54LOrIE+b/zzJqynTPrAeWacxlXagEZo65QtQZbVOFYrr'
  #{cipher} 를 앞에 붙히면 어플리케이션에게 암호화된 글자라는 의미를 전달하여 일반텍스트로 읽게하지 않는다.
dev:
  secret: dev-secret2