spring:
  datasource:
    url: jdbc:mysql://mysql/horse-live
    username: root
    password: test1357
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379