spring:
  datasource:
    url: jdbc:mysql://mysql/horse-live
    username: root
    password: test1357
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

application:
  security:
    jwt:
      secret-key: test
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days